server:
  servlet:
    context-path: /
  shutdown: graceful
spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5       # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true     # 自动提交
  data:
    redis:
      lettuce:
        pool:
          max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
          max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
          max-idle: 20    # 连接池中的最大空闲连接(默认8)
          min-idle: 5     # 连接池中的最小空闲连接(默认0)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.w4o.xx.core.entity
  global-config:
    banner: false
    db-config:
      # 解决逻辑删除，唯一键约束问题
      logic-delete-value: "null"
      logic-not-delete-value: 0
app:
  version: 0