server:
  servlet:
    context-path: /
  shutdown: graceful
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 600000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      filter:
        # sql 防注入
        wall:
          enabled: true
          db-type: mysql
          config:
            drop-table-allow: false
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.w4o.xx.core.entity
  global-config:
    banner: false
    db-config:
      # 解决逻辑删除，唯一键约束问题
      logic-delete-value: "null"
      logic-not-delete-value: 0
app:
  version: 0